spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/googleAuth
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    properties:
      hibernate:
        format-sql: true
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: // your cliend id
            client-secret: //your client secret

            scope:
              - email
              - profile

logging:
  level:
    org:
      springframework:
        security: TRACE
